# Generated by Django 3.2.2 on 2021-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='template',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='niftyfile',
            name='thumb_ipfs_hash',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='niftyfile',
            name='thumb_uri',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
